[Pipelines] Add better error message for missing --huggingface-repo-id (#53759)
Currently, if you run something like

```
//SDK/public/max-repo/pipelines/python:pipelines -- generate --use-gpu
--max-new-tokens 80 --max-length 1024 --num-warmups 0 --architecture
LlamaForCausalLM --cache-strategy naive
```

You get a stack trace and an unhelpful message:
```
TypeError: stat: path should be string, bytes, os.PathLike or integer,
not NoneType
```

This change addresses the final message.

MODULAR_ORIG_COMMIT_REV_ID: c331343b1107443ee8784fd42123496f9448642d